PROGRAMS_spu 	:= spu
LIBRARY_embed	:= lib_spu.a
IMPORTS		:= -lmisc

# make.footer

ifdef CELL_TOP
	include $(CELL_TOP)/buildutils/make.footer
else
	include /opt/cell/sdk/buildutils/make.footer
endif

